name: Build and Push to GCR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: codimite-assignment-444413 

    # Authenticate Docker to GCR
    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    # Build and Tag Docker Image
    - name: Build Docker Image
      run: |
        docker build -t gcr.io/codimite-assignment-444413/my-flask-app:latest ./microservice

    # Push Docker Image to GCR
    - name: Push Docker Image
      run: |
        docker push gcr.io/codimite-assignment-444413/my-flask-app:latest
